name: Daily Dependency Security Audit

on:
  schedule:
    - cron: '0 6 * * *' # daily 06:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-setup-install
        with:
          node-version: '20'
      - name: Run npm audit (high+ only)
        id: audit
        shell: bash
        run: |
          set +e
          npm audit --audit-level=high > audit.txt 2>&1
          status=$?
          echo "status=$status" >> $GITHUB_OUTPUT
          set -e
      - name: Upload audit artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit
          path: audit.txt
      - name: Create issue if vulnerabilities found
        if: steps.audit.outputs.status != '0'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('audit.txt', 'utf8').slice(0, 60000);
            const title = `Security audit detected vulnerabilities (${new Date().toISOString().split('T')[0]})`;
            const { data: issue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body: "Automated npm audit report:\n\n```\n" + body + "\n```",
              labels: ["security", "dependencies"]
            });
            core.info(`Created issue #${issue.number}`);
